config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/register", to: "users#new"
  resources :games, only: [:new, :create]


  # Routes for Google authentication
  get "/auth/:provider/callback", to: "sessions#googleAuth"
  get "/auth/failure", to: redirect("/")
  get "/profile", to: "users#show"


  resources :games, only:[:index, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates_presence_of :category, :difficulty, :number_of_questions, :custom_name
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :username, :email
  has_many :games
  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.username = auth.info.name
      user.email = auth.info.email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    render file: "public/404" if current_user.nil?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
  end

  def index
    @games = current_user.games
    @user = current_user
  end

  def create
    game = current_user.games.create(game_params)
    if game.save
      #QuestionAnswersApi.new(game).get_questions_and_answers
      redirect_to "/games"
    else
      flash[:error] = game.errors.full_messages.to_sentence
      redirect_to "/games/new"
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end

  private

  def game_params
    params.permit(:custom_name, :number_of_questions, :category, :difficulty)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @new ||= User.new
  end

  def log_in(user)
   session[:user_id] = user.id
  end

  def googleAuth
    # Get access tokens from the google server
    access_token = request.env["omniauth.auth"]
    user = User.from_omniauth(access_token)

    #See helper method above, creates session
    log_in(user)

    # Access_token is used to authenticate request made from the rails application to the google server
    user.google_token = access_token.credentials.token

    # Refresh_token to request new access_token
    # Note: Refresh_token is only sent once during the first request
    refresh_token = access_token.credentials.refresh_token

    user.google_refresh_token = refresh_token if refresh_token.present?

    user.save

    redirect_to games_path
  end

  def destroy
    session.delete(:user_id)
    current_user = nil
    redirect_to root_path
    flash[:success] = "You have been logged out! Come play again soon!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:new, :create]

  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def questions
    [
      ['1', '1'],
      ['2', '2'],
      ['3', '3'],
      ['4', '4'],
      ['5', '5'],
      ['6', '6'],
      ['7', '7'],
      ['8', '8'],
      ['9', '9'],
      ['10', '10'],
    ]
  end

  def categories
    [
      ['Geography', 'Geography'],
      ['History', 'History'],
      ['Books', 'Books'],
      ['Movies', 'Movies'],
      ['Television', 'Television'],
      ['Music', 'Music'],
      ['General Knowledge', 'General Knowledge'],
      ['Science & Nature', 'Science & Nature'],
    ]
  end

  def difficulties
    [
      ['Easy', 'easy'],
      ['Medium', 'medium'],
      ['Hard', 'hard'],
    ]
  end

  def convert_for_api_call_categories
    [
      ['Geography', '22'],
      ['History', '23'],
      ['Books', '10'],
      ['Movies', '11'],
      ['Television', '14'],
      ['Music', '12'],
      ['General Knowledge', '9'],
      ['Science & Nature', '17'],
    ]
  end
end

app/views/games/index.html.erb
<div class="container">
  <center><h2><%= @user.username %>'s Games</h2></center>
  <br>
  <center><h3><%= button_to "Create New Game" %></h3></center>
  <br>
  <br>
  <% unless @games.empty? %>
    <section class="games">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Game</th>
            <th scope="col">Category</th>
            <th scope="col">Difficulty</th>
            <th scope="col">Total Questions</th>
            <th scope="col"></th>
          </tr>
        </thead>

        <tbody>
            <% @games.each do |game| %>
              <section id='game-<%= game.id %>'>
                  <tr>
                    <td><%= game.custom_name %></td>
                    <td><%= game.category %></td>
                    <td><%= game.difficulty %></td>
                    <td><%= game.number_of_questions %></td>
                    <td>
                      <p><%= button_to "Start Game"%></p>
                      <p><%= button_to "Delete", game_path(id: game.id), method: :delete%></p>
                  </tr>
              </section>
            <% end %>
        </tbody>
      </table>
    </section>
  <% end %>
</div>

app/views/games/new.html.erb
<h1 class='display-3' align='center'> Create a Game! </h1>

<center>
  <%= form_tag "/games", method: :post do %>
    <%= label_tag "Customer name:" %>
    <%= text_field_tag :custom_name, nil, placeholder: "Name" %> <br>
    <%= label_tag "Total Number of Trivia Questions:" %>
    <%= select_tag(:number_of_questions, options_for_select(questions), {class: "select-field"}) %><br>
    <%= label_tag "Trivia Category:" %>
    <%= select_tag(:category, options_for_select(categories), {class: "select-field"}) %><br>
    <%= label_tag "Trivia Difficulty:" %>
    <%= select_tag(:difficulty, options_for_select(difficulties), {class: "select-field"}) %><br>
    <%= submit_tag('Create Game', class: "button") %>
  <% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TomatoTime</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/671a6667b5.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <topnav id="top-navbar">
  <nav class="navbar navbar-expand-lg">
    <i class="fa fa-carrot fa-3x" style="color: #51cf66;"></i>
     <a class="navbar-brand" href="/" style="font-size: 30px">TomatoTime</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
       <ul class="navbar-nav">
         <% if current_user.nil? %>
            <a class="nav-item nav-link active" href="/auth/google_oauth2">Login/Register with Google</a>
          <% else %>
            <a class="nav-item nav-link active" style="text-align: right" href="/games">My Games</a>
            <a class="nav-item nav-link active" style="text-align: right" href="/profile">Profile</a>
            <a class="nav-item nav-link active" style="text-align: right" href="/logout">Logout</a>
         <% end %>
       </ul>
     </div>

   </nav>
  </topnav>
    <% flash.each do |name, msg| %>
      <div class= "<%=name%>-flash">
        <p><%= msg %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%= @user.username %>

<h4>Your Game Stats</h4>

<h4>Number of Games Played</h4>

<h4>Number of Games Won</h4>

<h4>Number of Correctly Answered Questions</h4>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<h4>About Tomato Time:</h4>
<p>You can play all sorts of trivia games with your friends!</p>